version: '3'
services:
    bot:
        build: .
        env_file: 
            - ".env"
        ports:
            - "9999:8080"
        depends_on:
            - "db"
    db:
        image: "postgres:12"
        environment: 
            POSTGRES_USER: tagi
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: tagi
